const int = (value) => ({ __fire_int: value });
const double = (value) => ({ __fire_double: value });

export default [
  {
    ClassName: 'Artificial Intelligence',
    CourseNumber: 'CS 440',
    Description: 'Reviews for CS 440 Artificial Intelligence at UIUC. The course covers core AI topics including search, reasoning, planning, and learning.',
    DifficultyAvg: double(0),
    DifficultyCount: int(0),
    GraphicUrl: 'url(https://ws.engr.illinois.edu/images/block.i.color.png)',
    RatingAvg: double(0),
    RatingCount: int(0),
    SampleSyllabus: 'https://courses.grainger.illinois.edu/cs440/fa2025/syllabus.html',
    WorkloadAvg: double(0),
    WorkloadCount: int(0),
    category: ['Artificial Intelligence'],
    languages: ['Python'],
    season: {
      spring: true,
      summer: false,
      fall: true,
    },
  },
  {
    ClassName: 'AI Agents in the Wild',
    CourseNumber: 'CS 498',
    Description: 'Reviews for CS 498 AI Agents in the Wild at UIUC. The course focuses on practical AI agent systems, tool use, evaluation, and deployment patterns.',
    DifficultyAvg: double(0),
    DifficultyCount: int(0),
    GraphicUrl: 'url(https://ws.engr.illinois.edu/images/block.i.color.png)',
    RatingAvg: double(0),
    RatingCount: int(0),
    SampleSyllabus: '',
    WorkloadAvg: double(0),
    WorkloadCount: int(0),
    category: ['Artificial Intelligence', 'MCS Elective'],
    languages: ['Python'],
    season: {
      spring: true,
      summer: false,
      fall: true,
    },
  },
  {
    ClassName: 'Topics in Automated Deduction',
    CourseNumber: 'CS 576',
    Description: 'Reviews for CS 576 Topics in Automated Deduction at UIUC. The course focuses on theorem proving, SAT and SMT solving, and formal reasoning techniques.',
    DifficultyAvg: double(0),
    DifficultyCount: int(0),
    GraphicUrl: 'url(https://ws.engr.illinois.edu/images/block.i.color.png)',
    RatingAvg: double(0),
    RatingCount: int(0),
    SampleSyllabus: 'https://courses.grainger.illinois.edu/CS576/sp2026/policy.html',
    WorkloadAvg: double(0),
    WorkloadCount: int(0),
    category: ['Theory and Algorithms', 'MCS Advanced'],
    languages: [],
    season: {
      spring: true,
      summer: false,
      fall: false,
    },
  },
];
